items:
  - menu:
    - id: home
      label: Home
      href: '/jekyll-feature-rich.html'
    - id: blog
      label: Blog
      href: '/jekyll/blog/'
    - id: services
      label: Services
      href: '#'
    - id: contact
      label: Contact
      href: '#'
