---
---
locale: 'en'
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
backend:
  # See https://www.netlifycms.org/docs/authentication-backends/#github-backend
  name: github
  repo: dcycle/starterkit-jekyll
  branch: master
  base_url: https://auth.static.dcycle.com
  auth_endpoint: auth/github/alberto56
media_folder: 'docs/media'
public_folder: "/media"
collections:
  - name: "config"
    label: "General configuration"
    editor:
      preview: false
    files:
      - label: "General configuration"
        name: "config"
        create: false
        file: "docs/_data/config.yml"
        fields:
          - label: "Configuration"
            name: "items"
            widget: "list"
            fields:
              - label: "Menu items"
                name: "menu"
                widget: "list"
                fields:
                  - { label: 'id, for example home or blog', name: 'id', widget: 'string', required: false }
                  - { label: 'label, for example "Home" or "Blog"', name: 'label', widget: 'string' }
                  - { label: 'href, for example /blog/ or https://duckduckgo.com', name: 'href', widget: 'string' }
  - name: 'pages'
    create: true
    label: 'Pages'
    folder: 'docs/jekyll_pages/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path (for example /privacy-policy/)', name: 'permalink', widget: 'string' }
      - label: "Redirect From (for example /some-other-path/ ,/yet-another-path/)"
        name: "redirect_from"
        widget: "list"
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'events'
    create: true
    label: 'Events'
    folder: 'docs/jekyll_events/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path (for example /events/new-years-eve/)', name: 'permalink', widget: 'string' }
      - label: "Redirect From (for example /new-year/ ,/yet-another-path/)"
        name: "redirect_from"
        widget: "list"
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'blog'
    create: true
    label: 'Blog posts'
    folder: 'docs/jekyll_blogposts/_posts/'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path (for example /blog/my-blog-post/)', name: 'permalink', widget: 'string' }
      - label: "Redirect From (for example /blog/my-blog-post/ ,/yet-another-path/)"
        name: "redirect_from"
        widget: "list"
      - { label: 'Content', name: 'body', widget: 'markdown' }
